import 'package:cloud_firestore/cloud_firestore.dart';

class Beem {
  int? amount,
      balMeter,
      beemNo,
      beemSize,
      grossWt,
      lastYearRecMeter,
      loomNo,
      minStrg,
      name,
      pick,
      pipeNo,
      pipeWt,
      pno,
      recMeter,
      recTaka,
      reTaka2,
      rpm,
      tar,
      totalMetr,
      totalMeter2,
      totalMeterConsum,
      totalTaka,
      warparRate,
      yarnLotNo,
      yarnNetWt;

  String? addedBy,
      id,
      qualityCode,
      qualityName,
      warparName,
      warparCode,
      remark,
      yarnCode,
      yarnName;

  Timestamp? arrivingDate, loadingDate, endDate;

  Beem({
    this.addedBy,
    this.amount,
    this.balMeter,
    this.beemNo,
    this.beemSize,
    this.grossWt,
    this.id,
    this.lastYearRecMeter,
    this.loomNo,
    this.minStrg,
    this.name,
    this.pick,
    this.pipeNo,
    this.pipeWt,
    this.pno,
    this.qualityCode,
    this.qualityName,
    this.reTaka2,
    this.recMeter,
    this.recTaka,
    this.remark,
    this.rpm,
    this.tar,
    this.totalMeter2,
    this.totalMeterConsum,
    this.totalMetr,
    this.totalTaka,
    this.warparCode,
    this.warparName,
    this.warparRate,
    this.yarnCode,
    this.yarnLotNo,
    this.yarnName,
    this.yarnNetWt,
    this.arrivingDate,
    this.loadingDate,
    this.endDate,
  });

  factory Beem.fromJson(Map<String, dynamic> json) {
    return Beem(
      addedBy: json["added_by"],
      amount: json["amount"],
      arrivingDate: json["arriving_time"],
      balMeter: json["bal_meter"],
      beemNo: json["beem_no"],
      beemSize: json["beem_size"],
      endDate: json["end_date"],
      grossWt: json["gross_wt"],
      id: json["id"],
      lastYearRecMeter: json["last_year_rec_meter"],
      loadingDate: json["loading_date"],
      loomNo: json["loom_no"],
      minStrg: json["min_strg"],
      name: json["name"],
      pick: json["pick"],
      pipeNo: json["pipe_no"],
      pipeWt: json["pipe_wt"],
      pno: json["pno"],
      qualityCode: json["quality_code"],
      qualityName: json["quality_name"],
      reTaka2: json["rec_taka2"],
      recMeter: json["rec_meter"],
      recTaka: json["rec_taka"],
      remark: json["remark"],
      rpm: json["rpm"],
      tar: json["tar"],
      totalMeter2: json["total_meter2"],
      totalMeterConsum: json["total_meter_consum"],
      totalMetr: json["total_meter"],
      totalTaka: json["total_taka"],
      warparCode: json["warpar_code"],
      warparName: json["warpar_name"],
      warparRate: json["warpar_rate"],
      yarnCode: json["yarn_code"],
      yarnLotNo: json["yarn_lot_no"],
      yarnName: json["yarn_name"],
      yarnNetWt: json["yarn_net_wt"],
    );
  }
}
